# Generated by Django 5.0 on 2024-01-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email_adress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excert',
            new_name='excerpt',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=120),
        ),
    ]
